name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  LINT_AND_BUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: "https://registry.npmjs.org"
      - name: Install modules
        run: pnpm install
      - name: Run Lint
        run: pnpm lint